european-modelling-hubs/covid19-forecast-hub-europe

- code/validation/covid19.py
Adds extra check to return error and terminate validation if `forecast_date` is too close in time (<5 calendar days) to `target_end_date`. Should solve the problem of invalid submissions with a forecast date Tuesday or later which have a "1 wk ahead" target for that same week's Saturday. Fixes #70
> Fix #70: Error if forecast_date <5 days from target_end_date

- reports/ensemble/ensemble-report.Rmd
- reports/evaluation/evaluation-by-country.Rmd
- reports/evaluation/evaluation-report.Rmd
This removes all links from the ensemble and evaluation reports (which were originally designed to stand alone), and adapts text for use of the web site.
In doing so, this fixes #264 and #265.
> report text changes

- code/ensemble/EuroCOVIDhub/create-weekly-ensemble.R
- code/ensemble/utils/run-ensemble.R
Fixes a bug in `create-weekly-ensemble.R`.
- The weekly `forecast_date` was not properly used in filtering manual model exclusions (e.g. where a model was submitted late and should be excluded for one week only). 
- This meant that any model in the `manual-exclusions.csv` was excluded every week. 
- For weeks since 2021-04-05, two models have been excluded which should have been included in the ensemble. This affects past weekly ensemble forecasts for Germany and Poland (1-4 week cases and deaths).
Past ensembles will be updated with correct models in separate PR.
> Ensemble fix: manual exclusions by `forecast_date`

- code/evaluation/score_models.r
- code/reports/compile-evaluation-reports.r
- code/reports/ensemble/ensemble-report.Rmd
- data-truth/anomalies/anomalies.csv
- data-truth/anomalies/create-anomalies.R
This PR adds a csv noting which locations/target variables have anomalies affecting the weekly evaluation.
These values are excluded from evaluation.
This is really a placeholder before implementing an automated anomaly detection process.
> Exclude data anomalies from evaluation

- .github/workflows/README.md
As a newcomer to the repo, I needed a single place that summarises the different actions, whether they are scheduled or run on a specific action, etc.
I left some blanks in the `Function` column because I'm not sure what is the function of some actions yet. Feel free to fill the blanks if you feel like it.
This could be part of the wiki instead but I think it makes sense to have them in the same place as the actions themselves. And it will be cloned with the repository if someone wanted to spin off another forecast hub from this repo.
You can preview the result here: https://github.com/Bisaloo/covid19-forecast-hub-europe/tree/actions-readme/.github/workflows
> Create actions README

- code/config_utils/get_hub_config.R
Just to make it a little easier, adds a default to return all settings from `get_hub_config()` (i.e. the whole yaml).
> `get_hub_config()` returns all settings by default

- code/ensemble/EuroCOVIDhub/create-weekly-ensemble.R
- code/ensemble/methods/create-ensemble-relative-skill.R
- code/ensemble/utils/run-ensemble.R
Linked to [this discussion](https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/602#discussion_r663084918). I think it's fine to set the default in `run_ensemble` - we want all the function that (re-)create ensembles to use this default anyway, and don't want to rely on remembering to set this explicitly, I think.
> trying to update ensemble options to be more robust

- data-truth/README.Rmd
- data-truth/README.md
Adds text to the `data-truth` README Rmarkdown: 
- background on data sources (text taken from [wiki](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#truth-data))
- links out to data on vaccines, VoCs, and testing from ECDC.
> Link to ECDC data in `data-truth` README

- .github/workflows/ECDC.yml
- code/auto_download/ecdc_download.r
Adds daily hospital data from ECDC  to existing ECDC download script
- Data pulled from ECDC hosted source
- Access to source requires environment variables (/ github secrets)
- Filtered for data from a public source: one of Github API, Country API, Country website
- Formatted and saved in hub standard
- Data should be accessible using `covidHubUtils::load_truth()` - this just needs a quick PR into the package
Modifies Github action to support this:
- Data download run in existing github action
- Action updated to run daily
- Uses three additional secrets set in the github action
I also noticed some out of date code in the data download for ECDC cases and deaths (still using ISO-3 country codes, and we've found readr more reliable than vroom) so made those minor changes.
> Add hospital data

- .github/workflows/zoltar-upload.yml
Updates the github action to work with zoltar code in the submodule, as in https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/pull/18.
(Altogether this should close #105).
> Zoltar action works with submodule

- .github/workflows/zoltar-upload.yml
Zoltar uploads now work and we can update the GH action to run automatically. 
The workflow will run and show as successful even if nothing changed (it will only upload new files unless we direct otherwise, which would be a manual run). 
I've scheduled at 7am for no reason so whatever time is best.
> Run zoltar daily at 7am

- code/reports/rmdchunks/plot-forecasts.Rmd
At the moment filtering for the last X forecasts is done with `head`. This can lead to gaps when there are missing dates due to data issues, e.g. https://covid19forecasthub.eu/reports/evaluation-report-Ireland.html
This aims to fix this issue.
> better filtering for last X forecasts

- forecasthub.yml
Adds `inc hosp` as a target variable.
This should work with https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/pull/21 to mean that the validation accepts `{n} wk ahead inc hosp` as a valid target.
> Add `inc hosp` to hub config

- forecasthub.yml
Not much difference between mean and median scoring-wise but the hope is that this is more robust to outlier forecasts. Also this brings us in line with the US hub.
> Switch to median ensemble

- .gitignore
- .gitmodules
I'd like to add the `validation` folder to gitignore. It's a submodule in any case so shouldn't be changed from the main repo, so this should prevent accidental edits (or out of date versions of the submodule) being pushed alongside other commits.
> Add `validation` to `gitignore`

- .github/workflows/rebase-comment.yml
For security reasons, this is restricted to members of the epiforecasts organisation.
More generally, I prefer rebase to merging. It is a bit subjective but I find it makes the git history cleaner. 
For this reason, I also almost always 'rebase & merge' my PR instead of creating a merge commit: https://github.blog/2016-09-26-rebase-and-merge-pull-requests/
If the PR commit history is very messy and the change is relatively simple, I may opt for 'squash & merge'.
> Add GitHub action to automatically rebase PR when a comment with '/rebase' is posted.

- code/reports/rmdchunks/score-forecasts.Rmd
`scoringutils::compare_two_models` expects all columns except those being compared to be equal between models ([here](https://github.com/epiforecasts/scoringutils/blob/d09ff23e3cf9434606127ed145c315fedf9e1c40/R/pairwise-comparisons.R#L354)). Storing continuous weeks in the data frame before evaluating therefore creates a problem, as only those with the same number of continuous weeks of forecasts are being compared when calculating relative WIS/AE.
This fixes #823.
> don't store continuous weeks in evaluation

- code/reports/rmdchunks/ranking-table.Rmd
If `n_loc` has multiple values, this will throw a warning. Additionally, it there are multiple values but 1 is one of them (e.g. 1, 2, 3), the `n_loc` column will be removed.
This PR implements what I think was the intended goal.
> Fix warning logical of length > 1

- code/reports/rmdchunks/plot-forecasts.Rmd
This brings the plot in line with the text in the reports - I think this works better than the absolute numbers but it does require people to pay attention to the y axis which can require scrolling down if there are a lot of plots:
The alternative would be what we had before: divide by population for the ensemble reports (where it definitely makes sense for comparability) but keep absolute numbers for the country-by-country reports (where I feel less strongly), but that would require adjusting the text / legend / etc. in the code conditional on which report a plot is part of.
Fixes https://github.com/epiforecasts/covid19-forecast-hub-europe/issues/675.
> divide values by population size for plotting

- .github/workflows/ECDC.yml
- .github/workflows/JHU.yml
- .github/workflows/LANL.yml
- .github/workflows/baseline.yml
- .github/workflows/check-truth.yml
- .github/workflows/ensemble.yml
- .github/workflows/visualisation.yml
This should hopefully limit the number of GH actions failure simply due to the fact that something was pushed between the moment when the action started to run and the moment when it tries to push the output.
> Pull before attempting to push

- .github/workflows/reports-eval.yml
- code/reports/rmdchunks/plot-forecasts.Rmd
Plot limits for forecasts that exceed the data by a lot were lost in the recent refactor. This returns them to all ensemble/evaluation plots.
> bring back plot limits

- viz/prepare_forecast_data.py
This is a very temporary fix, which will hopefully soon be superseded by #801. However, it may be useful if we want to have hospitalizations on the angular dashboard as soon as possible.
> Add hospitalisations to json for visualization 

- data-truth/anomalies/anomalies.csv
- data-truth/anomalies/create-anomalies.R
We have updated the data source as of today (#1196), so forecasts for Switzerland made for this week should be excluded from evaluation.
> Exclude Switzerland from `inc hosp` forecasts this week

- code/reports/rmdchunks/get-config-vars.Rmd
I'm really not happy about this fix. The goal would be for everything to work when we change the config file, without having to keep a dictionary with nice labels for plots. The solution would be to use the nice labels directly in the raw data instead of abbreviated terms ('hosp') and to split 'inc case' into 'inc' and 'case'. Related: #708 and #796  
To do before it's ready to merge:
> Add hospitalisations to reports

- .github/workflows/visualisation.yml
Since we now get it via covidHubUtils.
Synchronize with https://github.com/epiforecasts/ForecastHubSubmissionApp/pull/9.
> Remove truth upload to app step

- data-processed/epiforecasts-weeklygrowth/metadata-epiforecasts-weeklygrowth.txt
Should mean that #1474 can be updated automatically and checks will work to validate forecasts, without failing because of missing metadata
> Add folder and metadata for epiforecasts-weeklygrowth

- code/evaluation/aggregate_scores.r
Fixes https://github.com/covid19-forecast-hub-europe/EuroForecastHub/issues/14
The `restrict-weeks` option was missing an argument and therefore `FALSE`, not `NULL` by default when run from the command line
> add argument to restrict-weeks

- .Rprofile
- .github/workflows/ECDC.yml
- .github/workflows/Validations-R.yml
- .github/workflows/baseline.yml
- .github/workflows/check-truth.yml
- .github/workflows/ensemble.yml
- .github/workflows/scoring.yml
- .github/workflows/submission_preview.yml
- .github/workflows/visualisation.yml
- renv.lock
- renv/.gitignore
- renv/activate.R
Partial fix for #1598.
This should make our actions much faster as well.
Currently, renv is also automatically used on our local computers. I think it's the best option since we can then be sure that we have the right environment to reproduce what happens on actions. However, if you'd prefer to use renv only in actions, I can add a switch for this.
> Set up renv for GitHub Actions

- code/validation/check_truth.py
- data-truth/README.Rmd
As to minimize conflicts if a workflow accidentally runs in a fork
> Do not include exact time in reports

- code/ensemble/EuroCOVIDhub/create-weekly-ensemble.R
This should probably be a config option but I'll leave it to @Bisaloo to decide that.
> specify minimum number of models in ensemble

- code/auto_download/hospitalisations/check-sources/README.md
- code/auto_download/hospitalisations/check-sources/select_hosp_sources.r
- code/auto_download/hospitalisations/check-sources/sources_update.csv
This is to keep an eye on whether we should switch / remove / add new hospitalisation sources, e.g. if it consistently gets selected for a while.
> set up monitoring of hospitalisation sources

- README.Rmd
- README.md
Following suggested website update: 
https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe-website/pull/48
> Update README citation to include Hub paper

- code/auto_download/hospitalisations-download.R
Downloading of hospitalisation data failed because the scraped data source can't be accessed. This removes downloading the scraped data sources for now (and it is not currently used anyway).
> remove downloading of scraped data source

- code/auto_download/check_revisions.R
Removes any empty (0-row) dataframes from data downloads - this was breaking the code, as in the recent [failing action](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/actions/runs/3838378448/jobs/6534764809#step:10:56).
This happened because the [most recent hospitalisation download](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/main/data-truth/ECDC/truth_ECDC-Incident%20Hospitalizations.csv) had 0-rows
> fix check_downloads() 

- code/reports/compile-country-reports.r
- code/reports/compile-model-reports.r
- code/reports/rmdchunks/model-score-table.Rmd
Fixes a problem where model reports fail when ensembles don't exist for any of the countries covered by a model. This happens more often now that the criterion of only creating ensembles when the number of models is `>2` is enforced.
Also adds a couple of messages to make future debugging easier.
> fix model reports

- .github/workflows/ECDC.yml
- .github/workflows/JHU.yml
- .github/workflows/check-truth.yml
- .github/workflows/create-parquet.yml
- .github/workflows/ensemble.yml
- .github/workflows/release.yml
- .github/workflows/render-readme.yml
- .github/workflows/reports-country.yml
- .github/workflows/reports-model.yml
- .github/workflows/scoring.yml
- .github/workflows/visualisation.yml
- .github/workflows/zoltar-upload.yml
We [continue](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/pull/2681) to have problems with Actions running on forks of the repo. These are difficult to control because it requires the fork owner to disable the actions. 
I suggest we add an if statement to all the Actions so they only run when our org (covid19-forecast-hub-europe) is the repo owner. (Following other people's experience of this [here](https://github.com/orgs/community/discussions/26704?sort=top))
Adding one example here then can copy to other actions if it seems like a good idea.
> Set actions to only run from this organisation

- .github/workflows/JHU.yml
- .github/workflows/ValidationV2.yml
- .github/workflows/Validations-R.yml
- .github/workflows/check-truth.yml
- .github/workflows/create-parquet.yml
- .github/workflows/ensemble.yml
- .github/workflows/hospitalisations.yml
- .github/workflows/release.yml
- .github/workflows/render-readme.yml
- .github/workflows/reports-country.yml
- .github/workflows/reports-model.yml
- .github/workflows/scoring.yml
- .github/workflows/submission_preview.yml
- .github/workflows/visualisation.yml
- .github/workflows/zoltar-upload.yml
Updated versions for github actions, copying from @Bisaloo PR over in the [submissions repo](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe-submissions/pull/20/files). 
I think this is the fix for #2635 ([failing scores](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/actions/runs/4102153348)).
> update actions versions

- code/auto_download/hospitalisations/process-owid.r
- data-truth/OWID/README.Rmd
- data-truth/OWID/README.md
- data-truth/OWID/truncated_OWID-Incident Hospitalizations.csv
- data-truth/OWID/truth_OWID-Incident Hospitalizations.csv
- data-truth/README.Rmd
I think target_end_date is clearer but this is currently breaking workflows.
> rename target_end_date -> date in data

- .github/workflows/submission_preview.yml
I am going through the docs for this feature again for another project and I think I figured out why pushes across different PR could sometimes cancel the workflow running in another PR.
Since `submission_preview.yml` is triggered by `pull_request_target`, `${{ github.ref }}` will always be `main`.
> Fix concurrency limitation in submission_preview.yml

- .github/workflows/hospitalisations.yml
Removing as web site is timing out
> remove case/death download from ECDC website

- code/ensemble/EuroCOVIDhub/create-weekly-ensemble.R
It seems a good idea to include the baseline in the ensemble as it provides regularisation. This PR makes that change.
> don't exclude the baseline from ensemble

- .renvignore
- DESCRIPTION
- renv.lock
- renv/activate.R
Some Github actions are currently failing. It seems that this is happening because they are downloading renv 1.0.0.
This PR is to test if this can be fixed by upgrading renv.
> update renv to 1.0.0

- .github/workflows/check-truth.yml
- .github/workflows/create-parquet.yml
- .github/workflows/ecdc_owid_data.yml
- .github/workflows/ensemble.yml
- .github/workflows/release.yml
- .github/workflows/render-readme.yml
- .github/workflows/reports-country.yml
- .github/workflows/reports-model.yml
- .github/workflows/scoring.yml
- .github/workflows/visualisation.yml
- .github/workflows/zoltar-upload.yml
The github Actions workflows have a check for the organisation names to ensure actions aren't run in forks. This PR updates this check to use the updated organisation name.
> update organisation name in actions

- viz/prepare_truth_data.R
Currently data that hasn't been updated for 4 weeks is not forwarded to the visualisation platform on the web site, which breaks some of the functionality there.
This PR adds legacy truth data to the web site visualisations.
> add legacy truth data to plotting

- data-processed/ICM-agentModel/2024-01-08-ICM-agentModel.csv
The ICM forecast of 8/1/24 was merged despite [not passing validation](https://github.com/european-modelling-hubs/covid19-forecast-hub-europe/actions/runs/7453247828/job/20304071596). This fixes the file by remove the final line.
Tagging for info @reneniehus @macrad.
> fix ICM forecast of 8/1/24
