european-modelling-hubs/covid19-forecast-hub-europe

- viz/prepare_forecast_data.py
This makes sure the `scenario_id` column exists and is set to something appropriate for every submission.
> fix visualisations by adding scenario columns one-by-one

- .github/workflows/ValidationV2.yml
Add yaml file that starts the new validation pipeline on pull requests.
The new pipeline is set up [here](https://github.com/epiforecasts/covid19-forecast-hub-europe-validations)
> ValidationsV2 yaml file

- .github/workflows/vis_val_eval.yml
Serves location file from data-locations directory and prepares metadata
> update github visualisation action

- reports/ensemble/ensemble-report.Rmd
- reports/ensemble/template-plot-ensemble.Rmd
This makes the data/forecasts more comparable between countries.
> report ensemble by population

- code/ensemble/utils/get_model_designations.r
useful e.g. for excluding "other" models from the ensemble
> function to get model designations

- .gitmodules
Adds [validation code](https://github.com/epiforecasts/covid19-forecast-hub-europe-validations) as a submodule. 
This should help make a start on testing checks locally (#187) as well as interacting with zoltar (#105, which currently relies on local validation code).
> Add validation as submodule

- code/reports/evaluation/evaluation-report.Rmd
- code/reports/evaluation/template-ranking-table.Rmd
adds 50 and 95 percent coverage to the table in the evaluation reports
> add coverage to forecast hub report

- .github/workflows/evaluation.yml
- .github/workflows/reports-ensemble.yml
- .github/workflows/reports-eval.yml
- code/evaluation/score_models.r
- code/reports/compile-ensemble-report.r
- code/reports/compile-evaluation-reports.r
- code/reports/ensemble/ensemble-report.Rmd
- code/reports/ensemble/template-plot-ensemble.Rmd
- code/reports/evaluation/evaluation-by-country.Rmd
These are a couple of fixes / simplifications I noticed while trying to get more familiar with the codebase. Let's hope I didn't already break something :crossed_fingers: 
I recommend reviewing this PR commit by commit as I grouped together related changes.
> Remove dependency to purrr and misc fixes

- data-truth/anomalies/anomalies.csv
- data-truth/anomalies/create-anomalies.R
- Adds anomalies in Spain and Ireland for week ending 2021-06-12
- This should remove these locations/targets from evaluation
> 2021-06-12 Remove anomalies from evaluation

- .github/workflows/README.md
- .github/workflows/zoltar-upload.yml
Creates github action for uploading to zoltar.
This action works off code on PR #105, but I've pulled the action out into a separate PR. This is so that we can merge the action and then use it to test PR #105 before merging that (by running the action on the #105 branch).
The action is currently on workflow dispatch only, with the idea to update to run at least once daily after we've tested and merged #105.
> Zoltar github action

- code/reports/rmdchunks/plot-forecasts.Rmd
> Set fig height dynamically

- code/reports/rmdchunks/plot-forecasts.Rmd
Trying to go for something more human-readable.
> Update x axis in plots

- code/auto_download/auto-download-lanl-covid19.r
Fixes problem in [action](https://github.com/epiforecasts/covid19-forecast-hub-europe/actions/runs/1032155817) introduced by adding a hospitalisation target in https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/672
Possibly simpler alternative would be to explicitly loop over only cases and deaths here, avoiding the failed http request.
> fix LANL autodownload script

- code/reports/rmdchunks/ranking-table.Rmd
Missed comment from https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/635#issuecomment-878358535
> Use scaled_rel_skill instead of relative_skill

- data-truth/README.Rmd
See https://github.com/epiforecasts/covid19-forecast-hub-europe/actions/runs/1147068578.
> Fix truth action

- code/reports/rmdchunks/score-forecasts.Rmd
> add AE to evaluation scores csv

- data-processed/itwm-dSEIR/metadata-itwm-dSEIR.txt
- viz/metadata.json
> Fix multiline string in yaml metadata file

- data-processed/schema-forecast.yml
- data-processed/schema-metadata.yml
instead of the kwalify one, for better compatibility with a wider range of libraries / languages.
> Add new schema based on jsonschema

- .github/labeler.yml
- .github/workflows/labeler.yml
~~On hold for now because I want to let the submission day pass as to not break anything for anyone before I get the chance to test it live.~~
Must be synced with https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/pull/24.
> Add separate action to label issues

- .github/workflows/reports-eval.yml
- code/evaluation/score_models.r
- code/reports/evaluation/evaluation-report.Rmd
- code/reports/rmdchunks/filter-forecasts.Rmd
- code/reports/rmdchunks/score-forecasts.Rmd
Updates to work with https://github.com/epiforecasts/EuroForecastHub/pull/5
> split scores

- data-processed/UNIPV-BayesINGARCHX/metadata-UNIPV-BayesINGARCHX.txt
> license update

- .github/workflows/ensemble.yml
- .github/workflows/reports-model.yml
> Reschedule Tuesday actions to GMT

- .github/workflows/scoring.yml
- code/evaluation/aggregate_scores.r
- code/evaluation/load_and_score_models.r
- code/evaluation/score_models.r
- forecasthub.yml
Rationale for this is that we may want to score ensembles residing in ensembles/data-processed separately and easily.
@Bisaloo perhaps `load_and_score_models` should become part of 
the `EuroForecastHub` package?
> improve usability of scoring code

- viz/prepare_forecast_data.py
81c50af48d19a93de22186f04200834f76b3dd8f: 122.6MB -> 121.6MB
942e1509fd6c2b453d0a9f4e2befaf49d6561aa8: 121.6MB -> 103.1MB
> Lighter json file

- .github/workflows/ECDC.yml
- code/auto_download/hospitalisations/get-non-eu.R
- Fix for #1359: Swiss hospitalisation data was stuck on a fixed date csv download.
- This uses the API for the same source, and the resulting daily values are identical, but now up to date.
- Many thanks for the code suggestion in the issue.
> Fix Switzerland hospitalisation data (#1359)

- .github/workflows/submission_preview.yml
> Cancel workflow in progress when a new commit is pushed

- .github/workflows/ECDC.yml
- .github/workflows/JHU.yml
- .github/workflows/baseline.yml
- .github/workflows/check-truth.yml
- .github/workflows/ensemble.yml
- .github/workflows/scoring.yml
> Remove unnecessary authentification & rebase before pushing

- .github/workflows/ECDC.yml
- .github/workflows/baseline.yml
- .github/workflows/check-truth.yml
- .github/workflows/ensemble.yml
- .github/workflows/scoring.yml
- .github/workflows/visualisation.yml
Fix #1629
Fix #1630 
This should make our actions slightly faster as well.
Past of #1598
> Use R version provided by container

- code/reports/compile-model-reports.r
As suggested by @jbracher. Obviously relative WIS won't make sense but it'll be good to see past forecasts vs. data, PITs etc.
> add a performance report for the baseline

- code/reports/rmdchunks/get-config-vars.Rmd
- code/reports/rmdchunks/insert-dropdowns.Rmd
baseline model reported is now created but not yet shown in the dropdown menu
> Show baseline

- code/reports/rmdchunks/plot-forecasts.Rmd
I haven't implemented the limit feature yet as I'm still to figure out a good way to do it.
> Update plot-forecasts to scoringutils 1.0.0

- .github/workflows/render-readme.yml
- README.Rmd
- README.md
- renv.lock
> Add hub citation in the README

- code/reports/rmdchunks/filter-forecasts.Rmd
- code/reports/rmdchunks/load-data.Rmd
> Add horizon 0 to data to connect truth and forecasts in plot

- code/reports/rmdchunks/model-score-plots.Rmd
> Add truth to plot legend

- viz/upload_to_azure.R
referenced by the visualisation app
> upload location file

- .Rbuildignore
- DESCRIPTION
- renv.lock
aims to fix the issue mentioned in https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/pull/2615#issuecomment-1357298009
> create explicit hubValidations dependency

- model-metadata/MOCOS-agent1.yml
- model-metadata/Statgroup19-richards.yml
- model-metadata/Statgroup19-spatialrichards.yml
Following feedback on the forecast hub ensemble paper by email (fixing directly in hub repo flows through into the paper + supplement).
> Fix errors in author metadata

- .github/workflows/ECDC.yml
- .github/workflows/JHU.yml
- .github/workflows/check-truth.yml
- .github/workflows/ensemble.yml
- .github/workflows/release.yml
- .github/workflows/reports-country.yml
- .github/workflows/reports-model.yml
- .github/workflows/scoring.yml
- .github/workflows/visualisation.yml
- .github/workflows/zoltar-upload.yml
> Use a single status issue per workflow

- .github/workflows/ECDC.yml
- code/auto_download/hospitalisations/get-ecdc-official.R
- code/auto_download/hospitalisations/get-ecdc-scraped.R
- code/auto_download/hospitalisations/get-non-eu.R
- code/auto_download/hospitalisations/get-owid.R
preparing for using hospitalisation data as is, this saves daily snapshots
> save dated files

- code/reports/rmdchunks/forecast-calibration.Rmd
fixes the error reported in https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/pull/2721#issuecomment-1396935841
> fix model report if no data

- code/auto_download/check_revisions.R
> prevent error on missing file in commit

- code/evaluation/aggregate_scores.r
- code/reports/rmdchunks/plot-forecasts.Rmd
- evaluation/weekly-summary/evaluation-2023-03-27.csv
- works with empty score tables as per https://github.com/covid19-forecast-hub-europe/EuroForecastHub/commit/18d0edfca9bf6b32f075cdc8e38b79ff1bca7ba9
- creates scores locally as github action is failing (related to #2868)
- doesn't show an NA model
> fix country reports

- code/evaluation/aggregate_scores.r
- renv.lock
see https://github.com/covid19-forecast-hub-europe/EuroForecastHub/pull/35
> less restrictive selection of forecasts to score

- evaluation/README.Rmd
> don't render README html

- README.Rmd
- README.md
Removing obsolete sections that are covered by the wiki
> remove obsolete sections from README

- .github/workflows/scoring.yml
I think this might fix the error in https://github.com/european-modelling-hubs/covid19-forecast-hub-europe/actions/runs/10770176911/job/29862993583
> install openblas for scoring
